### ISSUE TITLE
Allow using the mod ID instead of name for the artifact

### ISSUE THREAD

**Issue by Gaming32** [Deftu/Gradle-Toolkit#10]
Not all mod names are valid for Maven publishing, but all mod IDs are. For instance "World Host" is invalid (because it has a space), while "world-host" is valid. Additionally, I prefer my JARs to use the mod ID rather than the mod name.

**Comment by Deftu** [comment]
Added in 6c5ab999d17821d4d4dd88942ff7020cca804d29.
